version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: student_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-student_db}
      POSTGRES_USER: ${POSTGRES_USER:-student_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-student_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - student_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-student_user} -d ${POSTGRES_DB:-student_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Python API Service
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: student_api
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://student_user:student_pass@database:5432/student_db}
      - API_USERNAME=${API_USERNAME:-john123}
      - API_PASSWORD=${API_PASSWORD:-python}
      - DEBUG=${DEBUG:-false}
      - APP_VERSION=${APP_VERSION:-2.0.0}
      - PORT=5000
    depends_on:
      database:
        condition: service_healthy
    networks:
      - student_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # PHP Web Application
  webapp:
    build:
      context: ./services/webapp
      dockerfile: Dockerfile
    container_name: student_webapp
    environment:
      - API_URL=${API_URL:-http://api:5000}
      - API_USERNAME=${API_USERNAME:-john123}
      - API_PASSWORD=${API_PASSWORD:-python}
      - DEBUG=${DEBUG:-false}
      - APP_VERSION=${APP_VERSION:-2.0.0}
      - APP_TITLE=${APP_TITLE:-POZOS Student Management}
    depends_on:
      api:
        condition: service_healthy
    networks:
      - student_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: student_nginx
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
      - api
    networks:
      - student_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Docker Registry (for image storage)
  registry:
    image: registry:2
    container_name: student_registry
    ports:
      - "5001:5001"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - registry_data:/var/lib/registry
      - ./configs/registry/config.yml:/etc/docker/registry/config.yml:ro
    networks:
      - student_network
    restart: unless-stopped

  # Registry UI
  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: student_registry_ui
    ports:
      - "8081:80"
    environment:
      REGISTRY_URL: http://registry:5001
      REGISTRY_NAME: Student Management Registry
    depends_on:
      - registry
    networks:
      - student_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  registry_data:
    driver: local

networks:
  student_network:
    driver: bridge
    name: student_network
