version: '3.3'
services:
  webapp.student_list:
    image: webapp-pozos:1
    container_name: webapp_student_list
    depends_on:
      - pozos_api
    ports:
      - "80:80"
    environment:
      - USERNAME=john123
      - PASSWORD=python
    networks:
      - pozos_network

  pozos_api:
    image: api-pozos:1
    container_name: api_pozos
    ports:
      - "5000:5000"
    volumes:
      - './simple_api/:/data/'
    networks:
      - pozos_network

networks:
  pozos_network:
    name: pozos_network
    driver: bridge
